export const REQUEST_CARD = 'REQUEST_CARD';
export const FETCH_CARD_DATA = 'FETCH_CARD_DATA';
export const RECEIVE_CARD_DATA_COMPLETE = 'RECEIVE_CARD_DATA_COMPLETE';
export const RECEIVE_CARD_DATA_ERROR = 'RECEIVE_CARD_DATA_ERROR';
export const REQUEST_GUESTBOOK = 'REQUEST_GUESTBOOK';
export const FETCH_GUESTBOOK_DATA = 'FETCH_GUESTBOOK_DATA';
export const RECEIVE_GUESTBOOK_DATA_COMPLETE = 'RECEIVE_GUESTBOOK_DATA_COMPLETE';
export const RECEIVE_GUESTBOOK_DATA_ERROR = 'RECEIVE_GUESTBOOK_DATA_ERROR';
export const POST_GUESTBOOK = 'POST_GUESTBOOK';
export const POST_GUESTBOOK_COMPLETE = 'POST_GUESTBOOK_COMPLETE';
export const POST_GUESTBOOK_ERROR = 'POST_GUESTBOOK_ERROR';
export const RECEIVE_GUESTBOOK_ALL_DATA_COMPLETE = 'RECEIVE_GUESTBOOK_ALL_DATA_COMPLETE';
export const DELETE_GUESTBOOK_COMPLETE = 'DELETE_GUESTBOOK_COMPLETE';
export const DELETE_GUESTBOOK_ERROR = 'DELETE_GUESTBOOK_ERROR';

//admin
export const RECEIVE_CARD_LIST_DATA_COMPLETE = 'RECEIVE_CARD_LIST_DATA_COMPLETE';
export const RECEIVE_CARD_LIST_DATA_ERROR = 'RECEIVE_CARD_LIST_DATA_ERROR';
export const RECEIVE_CARD_ADMIN_DATA_COMPLETE = 'RECEIVE_CARD_ADMIN_DATA_COMPLETE';
export const RECEIVE_CARD_ADMIN_DATA_ERROR = 'RECEIVE_CARD_ADMIN_DATA_ERROR';
export const UPLOAD_COMPLETE = 'UPLOAD_COMPLETE';
export const CARD_DATA_UPDATE_COMPLETE = 'CARD_DATA_UPDATE_COMPLETE';
export const CARD_DATA_UPDATE_ERROR = 'CARD_DATA_UPDATE_ERROR';
